<template>
    <div class="relative">

        <button ref="flyoutTogglerBtn" @click="flyoutOpen = !flyoutOpen;" type="button"
            class="inline-flex btn btn-ghost dark:text-slate-100 btn-circle items-center gap-x-1 text-sm font-semibold leading-6"
            aria-expanded="false">
            <span><i class="fa-regular fa-message"></i></span>
        </button>


        <Transition name="flyout" mode="out-in">
            <div class="absolute right-0 z-10 mt-5 flex w-screen max-w-max px-4" v-if=" flyoutOpen ">
                <div ref="flyoutMenu"
                    class="w-screen max-w-md flex-auto overflow-hidden rounded-3xl bg-white text-sm leading-6 shadow-lg ring-1 ring-gray-900/5">
                    <div class="p-4">
                        <FlyoutMessage></FlyoutMessage>
                    </div>
                    <div class="grid grid-cols-1 divide-x divide-gray-900/5 bg-gray-50">
                        <RouterLink :to=" { } "
                            class="flex items-center justify-center gap-x-2.5 p-3 font-semibold text-gray-900 hover:bg-gray-100">
                            My Messages
                        </RouterLink>
                    </div>
                </div>
            </div>
        </Transition>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { onClickOutside } from '@vueuse/core'
import FlyoutMessage from "@/components/FlyoutMessage.vue";


const flyoutOpen = ref(false);
const flyoutMenu = ref(null);
const flyoutTogglerBtn = ref(null);


onClickOutside(flyoutMenu, () => {
    flyoutOpen.value = false;
}, {
    ignore: [flyoutTogglerBtn]
})



</script>

<style scoped>
.flyout-enter-active {
    -webkit-animation: flyout 0.5s cubic-bezier(0.190, 1.000, 0.220, 1.000) both;
    animation: flyout 0.5s cubic-bezier(0.190, 1.000, 0.220, 1.000) both;
}

.flyout-leave-active {

    -webkit-animation: flyout 0.5s cubic-bezier(0.950, 0.050, 0.795, 0.035) reverse both;
    animation: flyout 0.5s cubic-bezier(0.950, 0.050, 0.795, 0.035) reverse both;

}





/* ----------------------------------------------
 * Generated by Animista on 2023-5-3 15:56:58
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-bottom
 * ----------------------------------------
 */
@-webkit-keyframes flyout {
    0% {
        opacity: 0;
        -webkit-transform: translateY(-20px);
        transform: translateY(-20px);
    }

    100% {
        opacity: 1;
        -webkit-transform: translateY(0);
        transform: translateY(0);
    }
}

@keyframes flyout {
    0% {
        opacity: 0;
        -webkit-transform: translateY(-20px);
        transform: translateY(-20px);
    }

    100% {
        opacity: 1;
        -webkit-transform: translateY(0);
        transform: translateY(0);
    }
}
</style>